apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: rtz7lxhis-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/rtz7lxhis-java-quarkus-gitops